version: '3.4'

services:
  gamebackend:
    image: gamebackend
    build:
      context: .
      dockerfile: GameBackend/Dockerfile
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      SERVER_CONNECT_URI: tcp://gameagent:5555
    ports:
      - "8888:80"
  gameagent:
   image: gameagent
   build:
     context: GameAgent/.
     dockerfile: Dockerfile
   environment: 
    SERVER_LISTEN_URI: tcp://0.0.0.0:5555
# networks:
#   default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.10.1.0/24